services:
  postgres:
    image: postgres:16-alpine
    container_name: tm-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: tm-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  # (подключим позже)
  # app:
  #   build: .
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
  #     SPRING_DATASOURCE_USERNAME: taskuser
  #     SPRING_DATASOURCE_PASSWORD: taskpass
  #     SPRING_DATA_REDIS_HOST: redis
  #   ports:
  #     - "8080:8080"

volumes:
  pgdata:
  redisdata:
